# Generated by Django 4.2.16 on 2024-09-17 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_senior', models.BooleanField(default=False)),
                ('leave_days', models.ManyToManyField(blank=True, to='timetable.leaveday')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_type', models.CharField(choices=[('day', 'Day (07:00 - 15:00)'), ('evening', 'Evening (14:30 - 22:30)'), ('night', 'Night (22:00 - 07:30)'), ('off', 'Off')], max_length=10)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.nurse')),
            ],
        ),
    ]
