# .github/workflows/cicd.yml
name: CI/CD for Django project

on:
  push:
    branches:
      - pro  # main 브랜치로 푸시될 때만 동작

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install  

    - name: Run tests
      run: |
        poetry run python manage.py test  

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Deploy to EC2
      run: |
        ssh -i nursesProject.pem ubuntu@ec2-18-215-125-12.compute-1.amazonaws.com
        cd /smallProject
        git pull origin pro
        source /home/ubuntu/smallProject/venv/bin/activate
        python manage.py migrate 
        sudo systemctl restart nginx 
#      env:
#       SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # GitHub secrets에서 EC2의 SSH 키 설정
