# .github/workflows/cicd.yml

name: CI/CD for Django project

on:
  push:
    branches:
      - pro  # 'pro' 브랜치에 푸시될 때 실행

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
      working-directory: ./nursesTimetable  # pyproject.toml 파일이 있는 경로로 설정

    - name: Run tests
      run: |
        poetry run python manage.py test
      working-directory: ./nursesTimetable/nursestimetable  # manage.py 파일이 있는 경로로 설정

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH key and set permissions
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > nursesProject.pem
        chmod 600 nursesProject.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i nursesProject.pem ubuntu@ec2-18-215-125-12.compute-1.amazonaws.com << 'EOF'
        
        PID=\$(sudo lsof -t -i:8000)
        if [ ! -z "\$PID" ]; then
        sudo kill -9 \$PID
        fi

        cd /home/ubuntu/smallProject  
        git pull origin pro  

        source /home/ubuntu/.cache/pypoetry/virtualenvs/nursestimetable-KJ929Rd4-py3.12/bin/activate

        cd nursesTimetable/nursestimetable
        poetry run python manage.py migrate 

        sudo systemctl daemon-reload  
        sudo systemctl restart nginx 

        poetry run python manage.py runserver 0.0.0.0:8000  
        EOF


