name: CI/CD for Django project

on:
  push:
    branches:
      - pro  # 'pro' 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
      working-directory: ./nursesTimetable  # pyproject.toml 파일이 있는 경로로 설정

    - name: Stop Django server and update code
      run: |
        ssh -o StrictHostKeyChecking=no -i nursesProject.pem ubuntu@ec2-18-215-125-12.compute-1.amazonaws.com << 'EOF'
        
        # 최신 코드 가져오기
        cd /home/ubuntu/smallProject
        git pull origin pro
        EOF