name: CI for Django project

on:
  push:
    branches:
      - pro  # 'pro' 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Add SSH key and set permissions
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > nursesProject.pem
        chmod 600 nursesProject.pem

    - name: Git pull on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i nursesProject.pem ubuntu@ec2-18-215-125-12.compute-1.amazonaws.com << 'EOF'
        
        # 최신 코드 가져오기
        cd /home/ubuntu/smallProject
        git pull origin pro
        EOF

    - name: Clean up SSH key
      run: rm nursesProject.pem
